name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - mamba
  - pydata-sphinx-theme
  - empack

  - pip:
    - jupyterlite-core >= 0.1.0b19
    - jupyterlite-sphinx >= 0.8.0
    - jupyterlite-xeus-python >= 0.7.0
    - jupyterlab-night
